version: "3"
dotenv: [".env.local"]
tasks:
  app:env:
    cmds:
      - |
          secrets=$(grep -v '^#' .env.prod | grep '=' | sed 's/"/\\"/g' | tr '\n' ' ')
          fly secrets set $secrets -a hypr-server

  py:init: POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-cache --no-interaction --all-extras
  py:run: poetry run python3 {{.CLI_ARGS}}

  stripe: stripe listen --skip-verify --forward-to http://localhost:5000/webhook/stripe
  bacon: bacon {{.CLI_ARGS}}

  i18n:
    cmds:
      - |
          pnpm -F desktop lingui:extract |
          awk -F '│' '($2 ~ /[^ ]/ && $3 ~ /[0-9-]/) {
            gsub(/^ *| *$/, "", $2);
            gsub(/[^0-9-]/, "", $3);
            gsub(/^ *| *$/, "", $4);
            printf "{\"language\":\"%s\",\"total\":%d,\"missing\":%d}\n",
              $2,
              ($3 == "-" ? 0: $3),
              ($4 == "-" ? 0: $4)
          }' |
          jq -s . > ./apps/docs/data/i18n.json
