// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file v0.proto (package hypr.v0, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v0.proto.
 */
export const file_v0: GenFile = /*@__PURE__*/
  fileDesc("Cgh2MC5wcm90bxIHaHlwci52MCIfCg5TZXJ2ZXJUb0NsaWVudBINCgVhdWRpbxgBIAEoDCJPCg5DbGllbnRUb1NlcnZlchIPCgVhdWRpbxgBIAEoDEgAEiEKBmRldmljZRgCIAEoCzIPLmh5cHIudjAuRGV2aWNlSABCCQoHcGF5bG9hZCIhCgZEZXZpY2USCgoCaWQYASABKAkSCwoDa2V5GAIgASgJYgZwcm90bzM");

/**
 * @generated from message hypr.v0.ServerToClient
 */
export type ServerToClient = Message<"hypr.v0.ServerToClient"> & {
  /**
   * @generated from field: bytes audio = 1;
   */
  audio: Uint8Array;
};

/**
 * Describes the message hypr.v0.ServerToClient.
 * Use `create(ServerToClientSchema)` to create a new message.
 */
export const ServerToClientSchema: GenMessage<ServerToClient> = /*@__PURE__*/
  messageDesc(file_v0, 0);

/**
 * @generated from message hypr.v0.ClientToServer
 */
export type ClientToServer = Message<"hypr.v0.ClientToServer"> & {
  /**
   * @generated from oneof hypr.v0.ClientToServer.payload
   */
  payload: {
    /**
     * @generated from field: bytes audio = 1;
     */
    value: Uint8Array;
    case: "audio";
  } | {
    /**
     * @generated from field: hypr.v0.Device device = 2;
     */
    value: Device;
    case: "device";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message hypr.v0.ClientToServer.
 * Use `create(ClientToServerSchema)` to create a new message.
 */
export const ClientToServerSchema: GenMessage<ClientToServer> = /*@__PURE__*/
  messageDesc(file_v0, 1);

/**
 * @generated from message hypr.v0.Device
 */
export type Device = Message<"hypr.v0.Device"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string key = 2;
   */
  key: string;
};

/**
 * Describes the message hypr.v0.Device.
 * Use `create(DeviceSchema)` to create a new message.
 */
export const DeviceSchema: GenMessage<Device> = /*@__PURE__*/
  messageDesc(file_v0, 2);

