// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file v0.proto (package hypr.v0, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v0.proto.
 */
export const file_v0: GenFile = /*@__PURE__*/
  fileDesc("Cgh2MC5wcm90bxIHaHlwci52MCIlChRUcmFuc2NyaWJlSW5wdXRDaHVuaxINCgVhdWRpbxgBIAEoDCIlChVUcmFuc2NyaWJlT3V0cHV0Q2h1bmsSDAoEdGV4dBgBIAEoCWIGcHJvdG8z");

/**
 * @generated from message hypr.v0.TranscribeInputChunk
 */
export type TranscribeInputChunk = Message<"hypr.v0.TranscribeInputChunk"> & {
  /**
   * @generated from field: bytes audio = 1;
   */
  audio: Uint8Array;
};

/**
 * Describes the message hypr.v0.TranscribeInputChunk.
 * Use `create(TranscribeInputChunkSchema)` to create a new message.
 */
export const TranscribeInputChunkSchema: GenMessage<TranscribeInputChunk> = /*@__PURE__*/
  messageDesc(file_v0, 0);

/**
 * @generated from message hypr.v0.TranscribeOutputChunk
 */
export type TranscribeOutputChunk = Message<"hypr.v0.TranscribeOutputChunk"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message hypr.v0.TranscribeOutputChunk.
 * Use `create(TranscribeOutputChunkSchema)` to create a new message.
 */
export const TranscribeOutputChunkSchema: GenMessage<TranscribeOutputChunk> = /*@__PURE__*/
  messageDesc(file_v0, 1);

