/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as SettingsImport } from "./routes/settings";
import { Route as IndexImport } from "./routes/index";
import { Route as NotesIdImport } from "./routes/notes.$id";
import { Route as AuthSignUpImport } from "./routes/auth.sign-up";
import { Route as AuthSignInImport } from "./routes/auth.sign-in";
import { Route as AuthConnectImport } from "./routes/auth.connect";
import { Route as AuthConnectSuccessImport } from "./routes/auth.connect.success";
import { Route as AuthConnectFailedImport } from "./routes/auth.connect.failed";

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const NotesIdRoute = NotesIdImport.update({
  id: "/notes/$id",
  path: "/notes/$id",
  getParentRoute: () => rootRoute,
} as any);

const AuthSignUpRoute = AuthSignUpImport.update({
  id: "/auth/sign-up",
  path: "/auth/sign-up",
  getParentRoute: () => rootRoute,
} as any);

const AuthSignInRoute = AuthSignInImport.update({
  id: "/auth/sign-in",
  path: "/auth/sign-in",
  getParentRoute: () => rootRoute,
} as any);

const AuthConnectRoute = AuthConnectImport.update({
  id: "/auth/connect",
  path: "/auth/connect",
  getParentRoute: () => rootRoute,
} as any);

const AuthConnectSuccessRoute = AuthConnectSuccessImport.update({
  id: "/success",
  path: "/success",
  getParentRoute: () => AuthConnectRoute,
} as any);

const AuthConnectFailedRoute = AuthConnectFailedImport.update({
  id: "/failed",
  path: "/failed",
  getParentRoute: () => AuthConnectRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/connect": {
      id: "/auth/connect";
      path: "/auth/connect";
      fullPath: "/auth/connect";
      preLoaderRoute: typeof AuthConnectImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/sign-in": {
      id: "/auth/sign-in";
      path: "/auth/sign-in";
      fullPath: "/auth/sign-in";
      preLoaderRoute: typeof AuthSignInImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/sign-up": {
      id: "/auth/sign-up";
      path: "/auth/sign-up";
      fullPath: "/auth/sign-up";
      preLoaderRoute: typeof AuthSignUpImport;
      parentRoute: typeof rootRoute;
    };
    "/notes/$id": {
      id: "/notes/$id";
      path: "/notes/$id";
      fullPath: "/notes/$id";
      preLoaderRoute: typeof NotesIdImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/connect/failed": {
      id: "/auth/connect/failed";
      path: "/failed";
      fullPath: "/auth/connect/failed";
      preLoaderRoute: typeof AuthConnectFailedImport;
      parentRoute: typeof AuthConnectImport;
    };
    "/auth/connect/success": {
      id: "/auth/connect/success";
      path: "/success";
      fullPath: "/auth/connect/success";
      preLoaderRoute: typeof AuthConnectSuccessImport;
      parentRoute: typeof AuthConnectImport;
    };
  }
}

// Create and export the route tree

interface AuthConnectRouteChildren {
  AuthConnectFailedRoute: typeof AuthConnectFailedRoute;
  AuthConnectSuccessRoute: typeof AuthConnectSuccessRoute;
}

const AuthConnectRouteChildren: AuthConnectRouteChildren = {
  AuthConnectFailedRoute: AuthConnectFailedRoute,
  AuthConnectSuccessRoute: AuthConnectSuccessRoute,
};

const AuthConnectRouteWithChildren = AuthConnectRoute._addFileChildren(
  AuthConnectRouteChildren,
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/auth/connect": typeof AuthConnectRouteWithChildren;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/notes/$id": typeof NotesIdRoute;
  "/auth/connect/failed": typeof AuthConnectFailedRoute;
  "/auth/connect/success": typeof AuthConnectSuccessRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/auth/connect": typeof AuthConnectRouteWithChildren;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/notes/$id": typeof NotesIdRoute;
  "/auth/connect/failed": typeof AuthConnectFailedRoute;
  "/auth/connect/success": typeof AuthConnectSuccessRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/auth/connect": typeof AuthConnectRouteWithChildren;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/notes/$id": typeof NotesIdRoute;
  "/auth/connect/failed": typeof AuthConnectFailedRoute;
  "/auth/connect/success": typeof AuthConnectSuccessRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/auth/connect"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/notes/$id"
    | "/auth/connect/failed"
    | "/auth/connect/success";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings"
    | "/auth/connect"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/notes/$id"
    | "/auth/connect/failed"
    | "/auth/connect/success";
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/auth/connect"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/notes/$id"
    | "/auth/connect/failed"
    | "/auth/connect/success";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  AuthConnectRoute: typeof AuthConnectRouteWithChildren;
  AuthSignInRoute: typeof AuthSignInRoute;
  AuthSignUpRoute: typeof AuthSignUpRoute;
  NotesIdRoute: typeof NotesIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AuthConnectRoute: AuthConnectRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  NotesIdRoute: NotesIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings",
        "/auth/connect",
        "/auth/sign-in",
        "/auth/sign-up",
        "/notes/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/auth/connect": {
      "filePath": "auth.connect.tsx",
      "children": [
        "/auth/connect/failed",
        "/auth/connect/success"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth.sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth.sign-up.tsx"
    },
    "/notes/$id": {
      "filePath": "notes.$id.tsx"
    },
    "/auth/connect/failed": {
      "filePath": "auth.connect.failed.tsx",
      "parent": "/auth/connect"
    },
    "/auth/connect/success": {
      "filePath": "auth.connect.success.tsx",
      "parent": "/auth/connect"
    }
  }
}
ROUTE_MANIFEST_END */
