import { type Event } from "@hypr/plugin-db";

const createDate = (dayOffset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + dayOffset);
  return date.toISOString();
};

export const mockEvents: Event[] = [
  {
    id: "1",
    user_id: "user1",
    tracking_id: "track1",
    calendar_id: "cal1",
    name: "Morning Standup",
    note: "Daily team sync",
    start_date: createDate(0),
    end_date: createDate(0),
    google_event_url: null,
  },
  {
    id: "2",
    user_id: "user1",
    tracking_id: "track2",
    calendar_id: "cal1",
    name: "Lunch with Client",
    note: "Discuss new project requirements",
    start_date: createDate(0),
    end_date: createDate(0),
    google_event_url: null,
  },
  {
    id: "3",
    user_id: "user1",
    tracking_id: "track3",
    calendar_id: "cal1",
    name: "Product Demo",
    note: "Show new features to stakeholders",
    start_date: createDate(0),
    end_date: createDate(0),
    google_event_url: null,
  },
  {
    id: "4",
    user_id: "user1",
    tracking_id: "track4",
    calendar_id: "cal1",
    name: "Team Happy Hour",
    note: "Celebrate project milestone",
    start_date: createDate(0),
    end_date: createDate(0),
    google_event_url: null,
  },
  {
    id: "5",
    user_id: "user1",
    tracking_id: "track5",
    calendar_id: "cal1",
    name: "Project Review",
    note: "Review Q1 progress",
    start_date: createDate(1),
    end_date: createDate(1),
    google_event_url: null,
  },
  {
    id: "6",
    user_id: "user1",
    tracking_id: "track6",
    calendar_id: "cal1",
    name: "1:1 with Manager",
    note: "Weekly check-in",
    start_date: createDate(1),
    end_date: createDate(1),
    google_event_url: null,
  },
  {
    id: "7",
    user_id: "user1",
    tracking_id: "track7",
    calendar_id: "cal1",
    name: "Code Review",
    note: "Review PR #123",
    start_date: createDate(1),
    end_date: createDate(1),
    google_event_url: null,
  },
  {
    id: "8",
    user_id: "user1",
    tracking_id: "track8",
    calendar_id: "cal1",
    name: "Client Call",
    note: "Monthly check-in",
    start_date: createDate(3),
    end_date: createDate(3),
    google_event_url: null,
  },
  {
    id: "9",
    user_id: "user1",
    tracking_id: "track9",
    calendar_id: "cal1",
    name: "Planning",
    note: "Sprint planning",
    start_date: createDate(5),
    end_date: createDate(5),
    google_event_url: null,
  },
  {
    id: "10",
    user_id: "user1",
    tracking_id: "track10",
    calendar_id: "cal1",
    name: "Team Birthday",
    note: "Celebrate team birthdays",
    start_date: createDate(7),
    end_date: createDate(7),
    google_event_url: null,
  },
  {
    id: "11",
    user_id: "user1",
    tracking_id: "track11",
    calendar_id: "cal1",
    name: "Quarterly Planning",
    note: "Q2 planning session",
    start_date: createDate(10),
    end_date: createDate(10),
    google_event_url: null,
  },
  {
    id: "12",
    user_id: "user1",
    tracking_id: "track12",
    calendar_id: "cal1",
    name: "Budget Review",
    note: "Review department budget",
    start_date: createDate(10),
    end_date: createDate(10),
    google_event_url: null,
  },
  {
    id: "13",
    user_id: "user1",
    tracking_id: "track13",
    calendar_id: "cal1",
    name: "Team Lunch",
    note: "Team building activity",
    start_date: createDate(10),
    end_date: createDate(10),
    google_event_url: null,
  },
  {
    id: "15",
    user_id: "user1",
    tracking_id: "track15",
    calendar_id: "cal1",
    name: "Next Month Planning",
    note: "Early planning for next month",
    start_date: createDate(20),
    end_date: createDate(20),
    google_event_url: null,
  },
  {
    id: "16",
    user_id: "user1",
    tracking_id: "track16",
    calendar_id: "cal1",
    name: "Weekend Workshop",
    note: "Professional development",
    start_date: createDate(8),
    end_date: createDate(8),
    google_event_url: null,
  },
  {
    id: "17",
    user_id: "user1",
    tracking_id: "track17",
    calendar_id: "cal1",
    name: "Team Building",
    note: "Offsite activity",
    start_date: createDate(8),
    end_date: createDate(8),
    google_event_url: null,
  },
  {
    id: "18",
    user_id: "user1",
    tracking_id: "track18",
    calendar_id: "cal1",
    name: "Project Deadline",
    note: "Final submission",
    start_date: createDate(8),
    end_date: createDate(8),
    google_event_url: null,
  },
  {
    id: "19",
    user_id: "user1",
    tracking_id: "track19",
    calendar_id: "cal1",
    name: "Conference Call",
    note: "International partners",
    start_date: createDate(8),
    end_date: createDate(8),
    google_event_url: null,
  },
  {
    id: "20",
    user_id: "user1",
    tracking_id: "track20",
    calendar_id: "cal1",
    name: "Weekend Prep",
    note: "Prepare for next week",
    start_date: createDate(8),
    end_date: createDate(8),
    google_event_url: null,
  },
];
