/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/app'
import { Route as AppIndexImport } from './routes/app.index'
import { Route as AppNoteIdImport } from './routes/app.note.$id'
import { Route as AppNoteIdSubImport } from './routes/app.note.$id.sub'
import { Route as AppNoteIdMainImport } from './routes/app.note.$id.main'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppNoteIdRoute = AppNoteIdImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => AppRoute,
} as any)

const AppNoteIdSubRoute = AppNoteIdSubImport.update({
  id: '/sub',
  path: '/sub',
  getParentRoute: () => AppNoteIdRoute,
} as any)

const AppNoteIdMainRoute = AppNoteIdMainImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AppNoteIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/note/$id': {
      id: '/app/note/$id'
      path: '/note/$id'
      fullPath: '/app/note/$id'
      preLoaderRoute: typeof AppNoteIdImport
      parentRoute: typeof AppImport
    }
    '/app/note/$id/main': {
      id: '/app/note/$id/main'
      path: '/main'
      fullPath: '/app/note/$id/main'
      preLoaderRoute: typeof AppNoteIdMainImport
      parentRoute: typeof AppNoteIdImport
    }
    '/app/note/$id/sub': {
      id: '/app/note/$id/sub'
      path: '/sub'
      fullPath: '/app/note/$id/sub'
      preLoaderRoute: typeof AppNoteIdSubImport
      parentRoute: typeof AppNoteIdImport
    }
  }
}

// Create and export the route tree

interface AppNoteIdRouteChildren {
  AppNoteIdMainRoute: typeof AppNoteIdMainRoute
  AppNoteIdSubRoute: typeof AppNoteIdSubRoute
}

const AppNoteIdRouteChildren: AppNoteIdRouteChildren = {
  AppNoteIdMainRoute: AppNoteIdMainRoute,
  AppNoteIdSubRoute: AppNoteIdSubRoute,
}

const AppNoteIdRouteWithChildren = AppNoteIdRoute._addFileChildren(
  AppNoteIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppNoteIdRoute: typeof AppNoteIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppNoteIdRoute: AppNoteIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/note/$id': typeof AppNoteIdRouteWithChildren
  '/app/note/$id/main': typeof AppNoteIdMainRoute
  '/app/note/$id/sub': typeof AppNoteIdSubRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app': typeof AppIndexRoute
  '/app/note/$id': typeof AppNoteIdRouteWithChildren
  '/app/note/$id/main': typeof AppNoteIdMainRoute
  '/app/note/$id/sub': typeof AppNoteIdSubRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/note/$id': typeof AppNoteIdRouteWithChildren
  '/app/note/$id/main': typeof AppNoteIdMainRoute
  '/app/note/$id/sub': typeof AppNoteIdSubRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/'
    | '/app/note/$id'
    | '/app/note/$id/main'
    | '/app/note/$id/sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/app'
    | '/app/note/$id'
    | '/app/note/$id/main'
    | '/app/note/$id/sub'
  id:
    | '__root__'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/'
    | '/app/note/$id'
    | '/app/note/$id/main'
    | '/app/note/$id/sub'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/app",
        "/login",
        "/onboarding"
      ]
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/",
        "/app/note/$id"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/app/": {
      "filePath": "app.index.tsx",
      "parent": "/app"
    },
    "/app/note/$id": {
      "filePath": "app.note.$id.tsx",
      "parent": "/app",
      "children": [
        "/app/note/$id/main",
        "/app/note/$id/sub"
      ]
    },
    "/app/note/$id/main": {
      "filePath": "app.note.$id.main.tsx",
      "parent": "/app/note/$id"
    },
    "/app/note/$id/sub": {
      "filePath": "app.note.$id.sub.tsx",
      "parent": "/app/note/$id"
    }
  }
}
ROUTE_MANIFEST_END */
