/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppFinderRouteImport } from './routes/app.finder'
import { Route as AppControlRouteImport } from './routes/app.control'
import { Route as AppOrganizationIdRouteImport } from './routes/app.organization.$id'
import { Route as AppNoteIdRouteImport } from './routes/app.note.$id'
import { Route as AppHumanIdRouteImport } from './routes/app.human.$id'
import { Route as AppNoteEventIdRouteImport } from './routes/app.note.event.$id'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFinderRoute = AppFinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => AppRoute,
} as any)
const AppControlRoute = AppControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationIdRoute = AppOrganizationIdRouteImport.update({
  id: '/organization/$id',
  path: '/organization/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNoteIdRoute = AppNoteIdRouteImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHumanIdRoute = AppHumanIdRouteImport.update({
  id: '/human/$id',
  path: '/human/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNoteEventIdRoute = AppNoteEventIdRouteImport.update({
  id: '/note/event/$id',
  path: '/note/event/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/video': typeof VideoRoute
  '/app/control': typeof AppControlRoute
  '/app/finder': typeof AppFinderRoute
  '/app/new': typeof AppNewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/human/$id': typeof AppHumanIdRoute
  '/app/note/$id': typeof AppNoteIdRoute
  '/app/organization/$id': typeof AppOrganizationIdRoute
  '/app/note/event/$id': typeof AppNoteEventIdRoute
}
export interface FileRoutesByTo {
  '/video': typeof VideoRoute
  '/app/control': typeof AppControlRoute
  '/app/finder': typeof AppFinderRoute
  '/app/new': typeof AppNewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/human/$id': typeof AppHumanIdRoute
  '/app/note/$id': typeof AppNoteIdRoute
  '/app/organization/$id': typeof AppOrganizationIdRoute
  '/app/note/event/$id': typeof AppNoteEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/video': typeof VideoRoute
  '/app/control': typeof AppControlRoute
  '/app/finder': typeof AppFinderRoute
  '/app/new': typeof AppNewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/human/$id': typeof AppHumanIdRoute
  '/app/note/$id': typeof AppNoteIdRoute
  '/app/organization/$id': typeof AppOrganizationIdRoute
  '/app/note/event/$id': typeof AppNoteEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/video'
    | '/app/control'
    | '/app/finder'
    | '/app/new'
    | '/app/settings'
    | '/app/'
    | '/app/human/$id'
    | '/app/note/$id'
    | '/app/organization/$id'
    | '/app/note/event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/video'
    | '/app/control'
    | '/app/finder'
    | '/app/new'
    | '/app/settings'
    | '/app'
    | '/app/human/$id'
    | '/app/note/$id'
    | '/app/organization/$id'
    | '/app/note/event/$id'
  id:
    | '__root__'
    | '/app'
    | '/video'
    | '/app/control'
    | '/app/finder'
    | '/app/new'
    | '/app/settings'
    | '/app/'
    | '/app/human/$id'
    | '/app/note/$id'
    | '/app/organization/$id'
    | '/app/note/event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finder': {
      id: '/app/finder'
      path: '/finder'
      fullPath: '/app/finder'
      preLoaderRoute: typeof AppFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/control': {
      id: '/app/control'
      path: '/control'
      fullPath: '/app/control'
      preLoaderRoute: typeof AppControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization/$id': {
      id: '/app/organization/$id'
      path: '/organization/$id'
      fullPath: '/app/organization/$id'
      preLoaderRoute: typeof AppOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/note/$id': {
      id: '/app/note/$id'
      path: '/note/$id'
      fullPath: '/app/note/$id'
      preLoaderRoute: typeof AppNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/human/$id': {
      id: '/app/human/$id'
      path: '/human/$id'
      fullPath: '/app/human/$id'
      preLoaderRoute: typeof AppHumanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/note/event/$id': {
      id: '/app/note/event/$id'
      path: '/note/event/$id'
      fullPath: '/app/note/event/$id'
      preLoaderRoute: typeof AppNoteEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppControlRoute: typeof AppControlRoute
  AppFinderRoute: typeof AppFinderRoute
  AppNewRoute: typeof AppNewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHumanIdRoute: typeof AppHumanIdRoute
  AppNoteIdRoute: typeof AppNoteIdRoute
  AppOrganizationIdRoute: typeof AppOrganizationIdRoute
  AppNoteEventIdRoute: typeof AppNoteEventIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppControlRoute: AppControlRoute,
  AppFinderRoute: AppFinderRoute,
  AppNewRoute: AppNewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppHumanIdRoute: AppHumanIdRoute,
  AppNoteIdRoute: AppNoteIdRoute,
  AppOrganizationIdRoute: AppOrganizationIdRoute,
  AppNoteEventIdRoute: AppNoteEventIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
