// @ts-nocheck


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listCustomLlmModels() : Promise<string[]> {
    return await TAURI_INVOKE("plugin:connector|list_custom_llm_models");
},
async getCustomLlmModel() : Promise<string | null> {
    return await TAURI_INVOKE("plugin:connector|get_custom_llm_model");
},
async setCustomLlmModel(model: string) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_custom_llm_model", { model });
},
async getCustomLlmEnabled() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:connector|get_custom_llm_enabled");
},
async setCustomLlmEnabled(enabled: boolean) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_custom_llm_enabled", { enabled });
},
async getCustomLlmConnection() : Promise<Connection | null> {
    return await TAURI_INVOKE("plugin:connector|get_custom_llm_connection");
},
async setCustomLlmConnection(connection: Connection) : Promise<null> {
    return await TAURI_INVOKE("plugin:connector|set_custom_llm_connection", { connection });
},
async getLocalLlmConnection() : Promise<ConnectionLLM> {
    return await TAURI_INVOKE("plugin:connector|get_local_llm_connection");
},
async getLlmConnection() : Promise<ConnectionLLM> {
    return await TAURI_INVOKE("plugin:connector|get_llm_connection");
},
async getSttConnection() : Promise<ConnectionSTT> {
    return await TAURI_INVOKE("plugin:connector|get_stt_connection");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Connection = { api_base: string; api_key: string | null }
export type ConnectionLLM = { type: "HyprCloud"; connection: Connection } | { type: "HyprLocal"; connection: Connection } | { type: "Custom"; connection: Connection }
export type ConnectionSTT = { type: "HyprCloud"; connection: Connection } | { type: "HyprLocal"; connection: Connection }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
