const COMMANDS: &[&str] = &[
    "list_custom_llm_models",
    "get_custom_llm_model",
    "set_custom_llm_model",
    "get_custom_llm_enabled",
    "set_custom_llm_enabled",
    "get_local_llm_connection",
    "get_custom_llm_connection",
    "set_custom_llm_connection",
    "get_llm_connection",
    "get_stt_connection",
    "get_openai_api_key",
    "set_openai_api_key",
    "get_gemini_api_key",
    "set_gemini_api_key",
    "get_provider_source",
    "set_provider_source",
    "get_others_api_key",
    "set_others_api_key",
    "get_others_api_base",
    "set_others_api_base",
    "get_others_model",
    "set_others_model",
    "get_openai_model",
    "set_openai_model",
    "get_gemini_model",
    "set_gemini_model",
    "get_openrouter_model",
    "set_openrouter_model",
    "get_openrouter_api_key",
    "set_openrouter_api_key",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
