// @ts-nocheck

// This file has been generated by Specta. DO NOT EDIT.

export type Event = { id: string; calendar_id: string; platform: Platform; name: string; note: string; participants: Participant[]; start_date: string; end_date: string; google_event_url: string | null }

export type Participant = { name: string; email: string }

export type Platform = "Apple" | "Google"

export type Session = { id: number; timestamp: string; title: string; tags: string[]; audio_local_path: string | null; audio_remote_path: string | null; raw_memo_html: string; enhanced_memo_html: string | null; transcript: Transcript | null }

export type Transcript = { speakers: string[]; blocks: TranscriptBlock[] }

export type TranscriptBlock = { timestamp: string; text: string; speaker: string }

