// @ts-nocheck

// This file has been generated by Specta. DO NOT EDIT.

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

export type Session = { id: number; timestamp: string; title: string; tags: string[]; audio_local_path: string | null; audio_remote_path: string | null; raw_memo: JsonValue | null; enhanced_memo: JsonValue | null; transcript: Transcript | null }

export type Transcript = { speakers: string[]; blocks: TranscriptBlock[] }

export type TranscriptBlock = { timestamp: string; text: string; speaker: string }

