// @ts-nocheck

// This file has been generated by Specta. DO NOT EDIT.

export type ConfigDataProfile = { full_name: string | null; job_title: string | null; company_name: string | null; company_description: string | null; linkedin_username: string | null }

export type EnhanceRequest = { user: ConfigDataProfile; editor: JsonValue; template: Template }

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

export type NangoIntegration = "google-calendar" | "outlook-calendar"

export type RegenerateCheckoutUrlRequest = { external_customer_id: string }

export type RegenerateCheckoutUrlResponse = { customer: RegenerateCheckoutUrlResponseCustomer } | { status: number; error: string }

export type RegenerateCheckoutUrlResponseCustomer = { lago_customer_id: string; external_customer_id: string; payment_provider: string; checkout_url: string }

export type Template = { id: string; title: string; description: string; sections: TemplateSection[] }

export type TemplateSection = { title: string; description: string }

