// @ts-nocheck

// This file has been generated by Specta. DO NOT EDIT.

export type ConfigDataGeneral = { autostart: boolean; notifications: boolean; language: string; context: string }

export type ConfigDataProfile = { full_name: string | null; job_title: string | null; company_name: string | null; company_description: string | null; linkedin_username: string | null }

export type EnhanceRequest = { editor: string; config_general: ConfigDataGeneral; config_profile: ConfigDataProfile; transcript: Transcript; template: Template }

export type NangoIntegration = "google-calendar" | "outlook-calendar"

export type RegenerateCheckoutUrlRequest = { external_customer_id: string }

export type RegenerateCheckoutUrlResponse = { customer: RegenerateCheckoutUrlResponseCustomer } | { status: number; error: string }

export type RegenerateCheckoutUrlResponseCustomer = { lago_customer_id: string; external_customer_id: string; payment_provider: string; checkout_url: string }

export type Template = { id: string; title: string; description: string; sections: TemplateSection[] }

export type TemplateSection = { title: string; description: string }

export type Transcript = { blocks: TranscriptBlock[] }

export type TranscriptBlock = { start: number; end: number; text: string }

