// @ts-nocheck

// This file has been generated by Specta. DO NOT EDIT.

export type RegenerateCheckoutUrlRequest = { external_customer_id: string }

export type RegenerateCheckoutUrlResponse = { customer: RegenerateCheckoutUrlResponseCustomer } | { status: number; error: string }

export type RegenerateCheckoutUrlResponseCustomer = { lago_customer_id: string; external_customer_id: string; payment_provider: string; checkout_url: string }

