// @ts-nocheck

// This file has been generated by Specta. DO NOT EDIT.

export type ConnectInput = { c: string; f: string }

export type ConnectOutput = { key: string }

export type NangoConnectSessionRequest = { end_user: NangoConnectSessionRequestUser; organization?: NangoConnectSessionRequestOrganization | null; allowed_integrations: string[] }

export type NangoConnectSessionRequestOrganization = { id: string; display_name?: string | null }

export type NangoConnectSessionRequestUser = { id: string; display_name?: string | null; email?: string | null }

export type NangoConnectSessionResponse = { data: { token: string; expires_at: string } } | { error: { code: string } }

