on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/app/**
      - crates/**
  pull_request:
    branches:
      - main
    paths:
      - apps/app/**
      - crates/**
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_protoc
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/install_app_deps
      - uses: ./.github/actions/rust_install
      - uses: ./.github/actions/pnpm_install
      - run: pnpm -F ui build
      - run: pnpm -F app build
      - run: cargo build -p app
